time CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node 2 pretrain_w2v2.py \
--output_dir=training_output/pretrain_hf \
--logging_dir=tensorboard/pretrain \
--num_train_epochs=5 \
--logging_strategy=steps \
--logging_steps=10 \
--logging_first_step \
--per_device_train_batch_size=12 \
--per_device_eval_batch_size=1 \
--gradient_accumulation_steps=10 \
--save_total_limit=5 \
--evaluation_strategy=steps \
--eval_steps=1000 \
--save_strategy=steps \
--save_steps=2000 \
--learning_rate=0.001 \
--lr_scheduler_type=linear \
--warmup_ratio=0.1 \
--group_by_length \
--fp16=True \
--dataset_dir=/home/work/w2v2_pretrain/hf_datasets_aishell2 \
--model_name_or_path=/data2_from_58175/huggingface/models/wav2vec2-base/config.json \
--processor_path=processor \
--preprocessing_num_workers=8  \
--dataloader_num_workers=8  \
--freeze_feature_extractor=False  \
--prediction_loss_only=False  \
--verbose_log=False